FROM node:18-alpine

WORKDIR /app

# Копируем package.json и package-lock.json
COPY frontend/package*.json ./

# Устанавливаем зависимости
RUN npm install --legacy-peer-deps

# Копируем остальной код
COPY frontend/ .

# Сборка приложения
RUN npm run build

EXPOSE 3000

# Запуск приложения
CMD ["npm", "start"]