FROM golang:1.24-alpine

WORKDIR /app

COPY backend/backend-app/go.mod .
COPY backend/backend-app/go.sum .

RUN go mod download

COPY backend/backend-app /app

RUN go build -o main ./cmd/main.go

EXPOSE 8080

CMD ["./main"]