FROM golang:1.24-alpine

WORKDIR /app

# Копируем файлы с зависимостями
COPY go.mod go.sum ./

# Устанавливаем зависимости
RUN go mod download

# Копируем исходный код
COPY . .

# Запускаем тесты
CMD ["go", "test", "-v", "./internal/domain/repository/..."] 